import { useMemo, useState } from 'react'
import './styles.css'
import { retailStore } from './domain/retailStore'
import { checkout, type CartItem } from './domain/pos'
import { getImei, registerImei } from './domain/imei'

type Product = { id:string; name:string; brand:string; price:number; stock:number; trackImei:boolean }
type Repair = { id:string; customer:string; device:string; issue:string; status:'Received'|'Diagnosing'|'Ready'|'Completed' }
type Purchase = { id:string; supplier:string; items:number; total:number; status:'Draft'|'Ordered'|'Received' }
const nav=['Overview','POS','Inventory','Customers','Repairs','Purchasing','Analytics']
const icons=['⌂','▣','▤','♙','🔧','⇄','◒']
const money=(n:number)=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',maximumFractionDigits:0}).format(n)
const getProducts=():Product[]=>retailStore.products.map(p=>({id:p.id,name:p.name,brand:p.brand,price:p.price,trackImei:p.trackImei,stock:retailStore.inventory.find(i=>i.productId===p.id)?.quantity??0}))

function App(){
 const [active,setActive]=useState('Overview'),[aiOpen,setAiOpen]=useState(false),[query,setQuery]=useState('')
 const [cart,setCart]=useState<CartItem[]>([]),[paid,setPaid]=useState(''),[message,setMessage]=useState('')
 const [customers,setCustomers]=useState([...retailStore.customers]),[newCustomer,setNewCustomer]=useState({name:'',phone:''})
 const [repairs,setRepairs]=useState<Repair[]>([]),[repair,setRepair]=useState({customer:'',device:'',issue:''})
 const [purchases,setPurchases]=useState<Purchase[]>([]),[purchase,setPurchase]=useState({supplier:'',items:'',total:''})
 const [imeiInput,setImeiInput]=useState<Record<string,string>>({})
 const products=getProducts()
 const filtered=useMemo(()=>products.filter(p=>(p.name+p.brand).toLowerCase().includes(query.toLowerCase())),[query,products.length,retailStore.inventory.map(i=>i.quantity).join(',')])
 const addToCart=(p:Product)=>{
   const imei=imeiInput[p.id]?.trim()
   if(p.trackImei){ if(!imei) return setMessage('กรุณาระบุ IMEI 15 หลักสำหรับ '+p.name); if(!getImei(imei)){try{registerImei({imei,productId:p.id,branchId:retailStore.branches[0].id,status:'in_stock'})}catch(e){return setMessage(e instanceof Error?e.message:'IMEI error')} } }
   setCart(c=>{const f=c.find(x=>x.productId===p.id&&x.imei===(p.trackImei?imei:undefined));return f?c.map(x=>x===f?{...x,qty:x.qty+1}:x):[...c,{productId:p.id,name:p.name,qty:1,unitPrice:p.price,discount:0,imei:p.trackImei?imei:undefined}]});setMessage('')
 }
 const completeCheckout=()=>{try{const sale=checkout({tenantId:retailStore.tenant.id,branchId:retailStore.branches[0].id,items:cart,paid:Number(paid),paymentMethod:'cash'});setMessage('ชำระเงินสำเร็จ '+sale.id+' | เงินทอน '+money(sale.change));setCart([]);setPaid('')}catch(e){setMessage(e instanceof Error?e.message:'Checkout failed')}}
 const addCustomer=()=>{if(!newCustomer.name.trim()||!newCustomer.phone.trim())return setMessage('กรุณากรอกชื่อลูกค้าและเบอร์โทร');const c={id:'cus_'+Date.now(),tenantId:retailStore.tenant.id,name:newCustomer.name.trim(),phone:newCustomer.phone.trim(),loyaltyPoints:0};retailStore.customers.push(c);setCustomers([...retailStore.customers]);setNewCustomer({name:'',phone:''});setMessage('เพิ่มลูกค้าสำเร็จ')}
 const addRepair=()=>{if(!repair.customer||!repair.device||!repair.issue)return setMessage('กรอกข้อมูลงานซ่อมให้ครบ');setRepairs(x=>[...x,{id:'rep_'+Date.now(),...repair,status:'Received'}]);setRepair({customer:'',device:'',issue:''});setMessage('สร้างใบรับซ่อมสำเร็จ')}
 const advanceRepair=(id:string)=>setRepairs(x=>x.map(r=>r.id!==id?r:{...r,status:r.status==='Received'?'Diagnosing':r.status==='Diagnosing'?'Ready':r.status==='Ready'?'Completed':'Completed'}))
 const addPurchase=()=>{const items=Number(purchase.items),total=Number(purchase.total);if(!purchase.supplier||!Number.isFinite(items)||items<1||!Number.isFinite(total)||total<=0)return setMessage('กรอกข้อมูลสั่งซื้อให้ถูกต้อง');setPurchases(x=>[...x,{id:'po_'+Date.now(),supplier:purchase.supplier,items,total,status:'Draft'}]);setPurchase({supplier:'',items:'',total:''});setMessage('สร้าง Purchase Order สำเร็จ')}
 const receivePurchase=(id:string)=>setPurchases(x=>x.map(p=>p.id===id?{...p,status:'Received'}:p))
 const totalRevenue=retailStore.sales.reduce((s,x)=>s+x.total,0),stock=products.reduce((s,p)=>s+p.stock,0)
 const overview=()=> <><div className="hero"><div><div className="eyebrow">RETAILOS</div><h1>Business Overview <span>✦</span></h1><p>ข้อมูลจากการทำงานของ Demo Store</p></div><div className="heroBtns"><button className="secondary" onClick={()=>setActive('POS')}>＋ New Sale</button><button className="primary" onClick={()=>setAiOpen(true)}>✦ Ask AI</button></div></div><section className="kpis">{[['Revenue',money(totalRevenue)],['Orders',String(retailStore.sales.length)],['Products',String(products.length)],['Stock Units',String(stock)]].map(k=><div className="kpi" key={k[0]}><div className="kpiTop">{k[0]}</div><strong>{k[1]}</strong><div className="trend">Live session data</div></div>)}</section><InventoryTable products={filtered} onAdd={addToCart}/></>
 const pos=()=> <><div className="hero"><div><div className="eyebrow">POINT OF SALE</div><h1>POS Checkout</h1><p>สินค้า IMEI ต้องระบุหมายเลขก่อนเพิ่มลงตะกร้า</p></div></div><section className="grid2"><div className="card"><div className="cardHead"><div><h2>สินค้า</h2><span>เลือกเพื่อขาย</span></div></div><div className="quickGrid">{products.map(p=><div className="productTile" key={p.id}><b>{p.name}</b><small>{money(p.price)} {p.trackImei?'· IMEI':''}</small>{p.trackImei&&<input placeholder="IMEI 15 หลัก" value={imeiInput[p.id]??''} onChange={e=>setImeiInput(x=>({...x,[p.id]:e.target.value}))}/>}<button onClick={()=>addToCart(p)}>Add</button></div>)}</div></div><div className="card"><div className="cardHead"><div><h2>ตะกร้า</h2><span>{cart.length} รายการ</span></div></div><div className="tableWrap"><table><tbody>{cart.map(i=><tr key={i.productId+(i.imei??'')}><td>{i.name}{i.imei&&<small> · {i.imei}</small>}</td><td><button className="dots" onClick={()=>setCart(c=>c.map(x=>x===i?{...x,qty:Math.max(1,x.qty-1)}:x))}>−</button> {i.qty} <button className="dots" onClick={()=>setCart(c=>c.map(x=>x===i?{...x,qty:x.qty+1}:x))}>+</button></td><td>{money(i.qty*i.unitPrice)}</td></tr>)}</tbody></table></div><div className="cardHead"><h2>Total: {money(cart.reduce((s,i)=>s+i.qty*i.unitPrice,0)*1.07)}</h2></div><div className="actions"><input type="number" placeholder="จำนวนเงินที่รับ" value={paid} onChange={e=>setPaid(e.target.value)}/><button className="primary" onClick={completeCheckout}>ชำระเงิน</button></div></div></section></>
 const inventory=()=> <><div className="hero"><div><div className="eyebrow">INVENTORY</div><h1>Inventory Management</h1><p>ค้นหาและส่งสินค้าไป POS</p></div></div><InventoryTable products={filtered} onAdd={addToCart}/></>
 const customerView=()=> <div className="card module"><h1>Customers</h1><div className="formRow"><input placeholder="ชื่อลูกค้า" value={newCustomer.name} onChange={e=>setNewCustomer({...newCustomer,name:e.target.value})}/><input placeholder="เบอร์โทร" value={newCustomer.phone} onChange={e=>setNewCustomer({...newCustomer,phone:e.target.value})}/><button className="primary" onClick={addCustomer}>เพิ่มลูกค้า</button></div><div className="tableWrap"><table><thead><tr><th>NAME</th><th>PHONE</th><th>POINTS</th></tr></thead><tbody>{customers.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.phone}</td><td>{c.loyaltyPoints}</td></tr>)}</tbody></table></div></div>
 const repairView=()=> <div className="card module"><h1>Repairs</h1><div className="formRow"><input placeholder="ลูกค้า" value={repair.customer} onChange={e=>setRepair({...repair,customer:e.target.value})}/><input placeholder="อุปกรณ์" value={repair.device} onChange={e=>setRepair({...repair,device:e.target.value})}/><input placeholder="อาการเสีย" value={repair.issue} onChange={e=>setRepair({...repair,issue:e.target.value})}/><button className="primary" onClick={addRepair}>รับงานซ่อม</button></div>{repairs.map(r=><div className="listRow" key={r.id}><b>{r.customer} · {r.device}</b><span>{r.issue}</span><em>{r.status}</em><button onClick={()=>advanceRepair(r.id)}>Next status</button></div>)}</div>
 const purchasingView=()=> <div className="card module"><h1>Purchasing</h1><div className="formRow"><input placeholder="Supplier" value={purchase.supplier} onChange={e=>setPurchase({...purchase,supplier:e.target.value})}/><input type="number" placeholder="จำนวนรายการ" value={purchase.items} onChange={e=>setPurchase({...purchase,items:e.target.value})}/><input type="number" placeholder="ยอดรวม" value={purchase.total} onChange={e=>setPurchase({...purchase,total:e.target.value})}/><button className="primary" onClick={addPurchase}>สร้าง PO</button></div>{purchases.map(p=><div className="listRow" key={p.id}><b>{p.supplier}</b><span>{p.items} items · {money(p.total)}</span><em>{p.status}</em>{p.status!=='Received'&&<button onClick={()=>receivePurchase(p.id)}>Receive</button>}</div>)}</div>
 const analytics=()=> <div className="card module"><h1>Analytics</h1><section className="kpis"><div className="kpi"><div>Revenue</div><strong>{money(totalRevenue)}</strong></div><div className="kpi"><div>Orders</div><strong>{retailStore.sales.length}</strong></div><div className="kpi"><div>Average Order</div><strong>{retailStore.sales.length?money(totalRevenue/retailStore.sales.length):money(0)}</strong></div><div className="kpi"><div>Repairs</div><strong>{repairs.length}</strong></div></section><InventoryTable products={products} onAdd={addToCart}/></div>
 const view=active==='Overview'?overview():active==='POS'?pos():active==='Inventory'?inventory():active==='Customers'?customerView():active==='Repairs'?repairView():active==='Purchasing'?purchasingView():analytics()
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="brandMark">◈</div><div><b>RetailOS</b><span>AI Operating System</span></div></div><div className="workspace"><div className="avatar">M</div><div><b>Mobile Hub</b><span>1 branch · Pro</span></div></div><div className="sectionLabel">WORKSPACE</div><nav>{nav.map((n,i)=><button key={n} className={active===n?'navItem active':'navItem'} onClick={()=>{setActive(n);setMessage('')}}><span className="icon">{icons[i]}</span>{n}</button>)}</nav><div className="sectionLabel">INTELLIGENCE</div><button className="navItem aiNav" onClick={()=>setAiOpen(true)}>✦ AI Copilot <span className="live">LIVE</span></button></aside><main className="main"><header className="topbar"><div className="crumb">{active} <span>/</span> RetailOS</div><div className="topActions"><div className="globalSearch">⌕<input placeholder="Search products…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="miniAvatar">AS</div></div></header><div className="content">{message&&<div className="stateMessage" role="status">{message}</div>}{view}<footer>RetailOS Demo · <span>System online</span></footer></div></main>{aiOpen&&<div className="aiPanel"><div className="aiPanelTop"><div><div className="aiTitle">✦ AI Copilot</div><small>Session-aware demo assistant</small></div><button onClick={()=>setAiOpen(false)}>×</button></div><div className="aiChat"><div className="aiBubble"><b>Business summary</b><p>ยอดขาย {money(totalRevenue)} · {retailStore.sales.length} orders · สต็อก {stock} units</p></div></div></div>}</div>
}
function InventoryTable({products,onAdd}:{products:Product[];onAdd:(p:Product)=>void}){return <section className="card tableCard"><div className="cardHead"><div><h2>Inventory</h2><span>{products.length} products</span></div></div><div className="tableWrap"><table><thead><tr><th>PRODUCT</th><th>BRAND</th><th>PRICE</th><th>STOCK</th><th>ACTION</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><b>{p.name}</b>{p.trackImei&&' · IMEI'}</td><td>{p.brand}</td><td>{money(p.price)}</td><td>{p.stock} units</td><td><button className="linkBtn" onClick={()=>onAdd(p)}>Add to POS</button></td></tr>)}</tbody></table></div></section>}
export default App