import { useMemo, useState } from 'react'
import './styles.css'
import { retailStore } from './domain/retailStore'

type Product = { name: string; brand: string; price: string; stock: number; demand: 'High' | 'Medium' | 'Low' }
const nav = ['Overview', 'POS', 'Inventory', 'Customers', 'Repairs', 'Purchasing', 'Analytics']
const products: Product[] = retailStore.products.map((p) => ({
  name: p.name,
  brand: p.brand,
  price: new Intl.NumberFormat('th-TH', { style: 'currency', currency: 'THB', maximumFractionDigits: 0 }).format(p.price),
  stock: retailStore.inventory.find((i) => i.productId === p.id)?.quantity ?? 0,
  demand: (retailStore.inventory.find((i) => i.productId === p.id)?.quantity ?? 0) <= 5 ? 'High' : (retailStore.inventory.find((i) => i.productId === p.id)?.quantity ?? 0) <= 10 ? 'Medium' : 'Low',
}))
const kpis = [['Revenue', '฿1,284,500', '+12.8%'], ['Gross Profit', '฿318,240', '+8.4%'], ['Orders', '1,842', '+6.1%'], ['Stock Value', '฿4.82M', '-3.2%']]

function App() {
  const [active, setActive] = useState('Overview')
  const [aiOpen, setAiOpen] = useState(true)
  const [query, setQuery] = useState('')
  const filtered = useMemo(() => products.filter((p) => Object.values(p).join(' ').toLowerCase().includes(query.toLowerCase())), [query])
  return (
    <div className="app">
      <aside className="sidebar"><div className="brand"><div className="brandMark">◈</div><div><b>RetailOS</b><span>AI Operating System</span></div></div><div className="workspace"><div className="avatar">M</div><div><b>Mobile Hub</b><span>{retailStore.branches.length} branch · Pro</span></div><span className="chev">⌄</span></div><div className="sectionLabel">WORKSPACE</div><nav>{nav.map((item, i) => <button key={item} className={active === item ? 'navItem active' : 'navItem'} onClick={() => setActive(item)}><span className="icon">{['⌂', '▣', '▤', '♙', '🔧', '⇄', '◒'][i]}</span>{item}{item === 'POS' && <kbd>F2</kbd>}</button>)}</nav><div className="sectionLabel">INTELLIGENCE</div><button className="navItem aiNav" onClick={() => setAiOpen(true)}><span className="spark">✦</span>AI Copilot <span className="live">LIVE</span></button><div className="sidebarBottom"><button className="navItem"><span className="icon">⚙</span>Settings</button><div className="profile"><div className="avatar">AS</div><div><b>Alex Somchai</b><span>Owner · Admin</span></div><span>•••</span></div></div></aside>
      <main className="main"><header className="topbar"><div className="crumb">{active} <span>/</span> Business Overview</div><div className="topActions"><div className="globalSearch">⌕<input placeholder="Search anything…" value={query} onChange={(e) => setQuery(e.target.value)} /><kbd>⌘ K</kbd></div><button className="round">?</button><button className="round notify">♢<i /></button><div className="miniAvatar">AS</div></div></header>
        <div className="content"><div className="hero"><div><div className="eyebrow">MONDAY, AUGUST 24 · 2026</div><h1>Good morning, Alex <span>✦</span></h1><p>Here’s what’s happening across your retail business today.</p></div><div className="heroBtns"><button className="secondary">＋ New Sale</button><button className="primary" onClick={() => setAiOpen(true)}>✦ Ask AI</button></div></div>
          <section className="kpis">{kpis.map((k) => <div className="kpi" key={k[0]}><div className="kpiTop"><span>{k[0]}</span><button>•••</button></div><strong>{k[1]}</strong><div className="trend"><em>{k[2]}</em><span>vs last 30 days</span></div></div>)}</section>
          <section className="grid2"><div className="card chartCard"><div className="cardHead"><div><h2>Revenue performance</h2><span>Sales across all branches</span></div><select><option>Last 30 days</option><option>Last 7 days</option></select></div><div className="chart"><div className="ylabels"><span>฿120K</span><span>฿90K</span><span>฿60K</span><span>฿30K</span><span>฿0</span></div><svg viewBox="0 0 700 250" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#7c6cff" stopOpacity=".26" /><stop offset="1" stopColor="#7c6cff" stopOpacity="0" /></linearGradient></defs><path d="M0 210 C55 200 70 175 110 185 S160 215 205 165 S250 120 285 145 S330 175 365 120 S420 70 455 115 S500 150 540 80 S600 55 640 95 S675 55 700 35 L700 250 L0 250Z" fill="url(#fill)" /><path d="M0 210 C55 200 70 175 110 185 S160 215 205 165 S250 120 285 145 S330 175 365 120 S420 70 455 115 S500 150 540 80 S600 55 640 95 S675 55 700 35" fill="none" stroke="#8172ff" strokeWidth="4" strokeLinecap="round" /></svg><div className="xlabels"><span>Jul 25</span><span>Aug 1</span><span>Aug 8</span><span>Aug 15</span><span>Aug 24</span></div></div></div><div className="card health"><div className="cardHead"><div><h2>Business health</h2><span>AI-powered business pulse</span></div><span className="status"><i /> Healthy</span></div><div className="healthBody"><div className="score"><div className="ring"><b>87</b><span>/ 100</span></div><small>Excellent</small></div><div className="healthBars">{[['Sales velocity', 92], ['Inventory', 81], ['Profitability', 89], ['Customers', 91], ['Cash flow', 76]].map(([name, value]) => <div key={name as string}><span>{name}</span><b>{value}</b><div><i style={{ width: `${value}%` }} /></div></div>)}</div></div><div className="healthFooter">✦ <span>AI detected <b>2 opportunities</b> and <b>1 item to watch.</b></span><button onClick={() => setAiOpen(true)}>Review →</button></div></div></section>
          <section className="grid3"><div className="card aiInsight"><div className="aiHeader"><div className="aiIcon">✦</div><div><h2>AI Insight</h2><span>Just now · Autonomous analysis</span></div><span className="pulse">● LIVE</span></div><h3>Inventory opportunity detected</h3><p>Galaxy S26 Ultra is selling <b>28% slower</b> than its 14-day average while 41 units remain in stock.</p><div className="recommend"><div><span>Recommended action</span><b>Bundle promotion · 5% incentive</b></div><strong>+23% <small>sell-through</small></strong></div><div className="actions"><button onClick={() => setAiOpen(true)}>Review analysis</button><button className="primary">Create promotion</button></div></div><div className="card quick"><div className="cardHead"><div><h2>Quick actions</h2><span>Common workflows</span></div></div><div className="quickGrid">{[['＋', 'New sale'], ['▤', 'Add inventory'], ['♙', 'New customer'], ['🔧', 'Repair ticket'], ['⇄', 'Transfer stock'], ['◒', 'AI forecast']].map(([icon, label]) => <button key={label} onClick={() => setActive(label)}><span>{icon}</span>{label}</button>)}</div></div></section>
          <section className="card tableCard"><div className="cardHead"><div><h2>Inventory overview</h2><span>Real-time stock across {retailStore.branches.length} branch</span></div><button className="linkBtn" onClick={() => setActive('Inventory')}>View inventory →</button></div><div className="tableWrap"><table><thead><tr><th>PRODUCT</th><th>BRAND</th><th>PRICE</th><th>STOCK</th><th>DEMAND</th><th /></tr></thead><tbody>{filtered.map((p) => <tr key={p.name}><td><div className="product"><div className="device">▣</div><b>{p.name}</b></div></td><td>{p.brand}</td><td><b>{p.price}</b></td><td>{p.stock} units</td><td><span className={`demand ${p.demand.toLowerCase()}`}>{p.demand}</span></td><td><button className="dots">•••</button></td></tr>)}</tbody></table></div></section><footer>RetailOS v1.0 · <span>All systems operational</span><div>Privacy · Security · Documentation</div></footer></div></main>
      {aiOpen && <div className="aiPanel"><div className="aiPanelTop"><div><div className="aiTitle"><span>✦</span> AI Copilot</div><small>Your business intelligence layer</small></div><button onClick={() => setAiOpen(false)}>×</button></div><div className="aiChat"><div className="aiBubble"><b>Good morning, Alex.</b><p>I’ve analyzed your business data. There are <strong>2 opportunities</strong> worth your attention today.</p></div><div className="suggestion"><span>✦</span><div><b>Reduce stock risk</b><small>Live inventory analysis</small></div><button>Review</button></div><div className="suggestion"><span>↗</span><div><b>Upsell opportunity</b><small>Accessory attach-rate analysis</small></div><button>Explore</button></div></div><div className="aiPrompt"><input placeholder="Ask anything about your business…" /><button>➤</button></div><div className="aiNote">AI uses your live business data · Recommendations require approval</div></div>}
    </div>
  )
}
export default App
