import { useMemo, useState } from 'react'
import './styles.css'
import { retailStore } from './domain/retailStore'
import { checkout, type CartItem } from './domain/pos'
import { getImei, registerImei } from './domain/imei'

type Product={id:string;name:string;brand:string;price:number;stock:number;trackImei:boolean}
type Repair={id:string;customer:string;device:string;issue:string;status:'Received'|'Diagnosing'|'Ready'|'Completed'}
type Purchase={id:string;supplier:string;items:number;total:number;status:'Draft'|'Ordered'|'Received'}
const money=(n:number)=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',maximumFractionDigits:0}).format(n)
const todayLabel=()=>new Intl.DateTimeFormat('th-TH',{day:'numeric',month:'long',year:'numeric'}).format(new Date())
const todayShortLabel=()=>new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date())
const products=():Product[]=>retailStore.products.map(p=>({id:p.id,name:p.name,brand:p.brand,price:p.price,trackImei:p.trackImei,stock:retailStore.inventory.find(i=>i.productId===p.id)?.quantity??0}))
const navGroups=[{label:'CORE',items:[['Dashboard','⌂'],['POS','▣'],['Products','◫'],['IMEI Inventory','▥'],['Stock & Transfer','⇄'],['Purchases','🛒']]},{label:'CUSTOMER',items:[['Customers (CRM)','♙'],['Loyalty & Points','✧'],['Installment','▤']]},{label:'SERVICE',items:[['Repair Center','🔧'],['Trade-In (รับซื้อ)','♻']]},{label:'FINANCE',items:[['Accounting','▤'],['Reports & Analytics','▥']]},{label:'AI & AUTOMATION',items:[['AI Copilot','✦'],['AI Insights','◈'],['Automation','⚙'],['Apps & Integrations','⌘'],['Settings','⚙']]}] as const

function App(){
 const [active,setActive]=useState('Dashboard'),[query,setQuery]=useState(''),[aiOpen,setAiOpen]=useState(true),[cart,setCart]=useState<CartItem[]>([]),[paid,setPaid]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('')
 const [customers,setCustomers]=useState([...retailStore.customers]),[newCustomer,setNewCustomer]=useState({name:'',phone:''}),[repairs,setRepairs]=useState<Repair[]>([]),[repair,setRepair]=useState({customer:'',device:'',issue:''}),[purchases,setPurchases]=useState<Purchase[]>([]),[purchase,setPurchase]=useState({supplier:'',items:'',total:''}),[imeiInput,setImeiInput]=useState<Record<string,string>>({})
 const allProducts=products()
 const filtered=useMemo(()=>allProducts.filter(p=>(p.name+p.brand).toLowerCase().includes(query.toLowerCase())),[query,allProducts.length,retailStore.inventory.map(i=>i.quantity).join(',')])
 const totalRevenue=retailStore.sales.reduce((s,x)=>s+x.total,0)
 const orderCount=retailStore.sales.length
 const unitsSold='—'
 const averageOrder=orderCount?totalRevenue/orderCount:0
 const runAction=(fn:()=>void)=>{setError('');setLoading(true);try{fn()}catch(e){setError(e instanceof Error?e.message:'เกิดข้อผิดพลาด')}finally{setLoading(false)}}
 const addToCart=(p:Product)=>{const imei=imeiInput[p.id]?.trim();if(p.trackImei){if(!imei)return setMessage('กรุณาระบุ IMEI 15 หลักสำหรับ '+p.name);if(!getImei(imei)){try{registerImei({imei,productId:p.id,branchId:retailStore.branches[0].id,status:'in_stock'})}catch(e){return setMessage(e instanceof Error?e.message:'IMEI error')}}}setCart(c=>{const f=c.find(x=>x.productId===p.id&&x.imei===(p.trackImei?imei:undefined));return f?c.map(x=>x===f?{...x,qty:x.qty+1}:x):[...c,{productId:p.id,name:p.name,qty:1,unitPrice:p.price,discount:0,imei:p.trackImei?imei:undefined}]});setMessage('')}
 const completeCheckout=()=>{try{const sale=checkout({tenantId:retailStore.tenant.id,branchId:retailStore.branches[0].id,items:cart,paid:Number(paid),paymentMethod:'cash'});setMessage('ชำระเงินสำเร็จ '+sale.id+' | เงินทอน '+money(sale.change));setCart([]);setPaid('')}catch(e){setMessage(e instanceof Error?e.message:'Checkout failed')}}
 const addCustomer=()=>{if(!newCustomer.name.trim()||!newCustomer.phone.trim())return setMessage('กรุณากรอกชื่อลูกค้าและเบอร์โทร');retailStore.customers.push({id:'cus_'+Date.now(),tenantId:retailStore.tenant.id,name:newCustomer.name.trim(),phone:newCustomer.phone.trim(),loyaltyPoints:0});setCustomers([...retailStore.customers]);setNewCustomer({name:'',phone:''});setMessage('เพิ่มลูกค้าสำเร็จ')}
 const addRepair=()=>{if(!repair.customer||!repair.device||!repair.issue)return setMessage('กรอกข้อมูลงานซ่อมให้ครบ');setRepairs(x=>[...x,{id:'rep_'+Date.now(),...repair,status:'Received'}]);setRepair({customer:'',device:'',issue:''});setMessage('สร้างใบรับซ่อมสำเร็จ')}
 const addPurchase=()=>{const items=Number(purchase.items),total=Number(purchase.total);if(!purchase.supplier||items<1||total<=0)return setMessage('กรอกข้อมูลสั่งซื้อให้ถูกต้อง');setPurchases(x=>[...x,{id:'po_'+Date.now(),supplier:purchase.supplier,items,total,status:'Draft'}]);setPurchase({supplier:'',items:'',total:''});setMessage('สร้าง Purchase Order สำเร็จ')}
 const Dashboard=()=> <div className="dashboard">
  <div className="dashHead"><div><h1>Good morning, Admin! 👋</h1><p>ภาพรวมธุรกิจประจำวันที่ {todayLabel()}</p></div><div className="filters"><button>▣ {todayShortLabel()}</button><button>⚙ Filter</button><button>•••</button></div></div>
  <section className="metricGrid">{[['💵','Total Revenue',money(totalRevenue),orderCount?'ยอดขายจากข้อมูลจริง':'ยังไม่มีรายการขาย'],['▥','Gross Profit',money(0),'ยังไม่มีข้อมูลต้นทุนสินค้า'],['▤','Orders',String(orderCount),'จำนวนออเดอร์ที่บันทึกจริง'],['📦','Units Sold',unitsSold,'ยังไม่มี line-item sales data'],['🛒','Avg. Order Value',money(averageOrder),orderCount?'คำนวณจากยอดขายจริง':'ยังไม่มีรายการขาย'],['◔','Profit Margin','—','รอข้อมูลต้นทุนสินค้า']].map((m,i)=><div className="metric" key={m[1]}><span className={'metricIcon c'+i}>{m[0]}</span><div><small>{m[1]}</small><b>{m[2]}</b><em className={i===5?'down':''}>{m[3]}</em></div></div>)}</section>
  <div className="dashboardLayout"><section className="mainDash">
   <div className="card salesCard"><div className="cardTitle"><h2>Sales Overview</h2><span>● Revenue &nbsp; ● Profit</span></div><div className="chartArea"><div className="yAxis"><i>1.0M</i><i>800K</i><i>600K</i><i>400K</i><i>0</i></div><svg viewBox="0 0 700 260" preserveAspectRatio="none"><polyline className="revLine" points="0,200 70,150 140,90 210,110 280,70 350,130 420,115 490,160 560,125 630,150 700,45"/><polyline className="profitLine" points="0,220 70,190 140,170 210,180 280,165 350,205 420,190 490,210 560,195 630,205 700,165"/></svg><div className="xAxis"><i>17 May</i><i>18 May</i><i>19 May</i><i>20 May</i><i>21 May</i><i>22 May</i><i>23 May</i></div></div></div>
   <div className="card"><div className="cardTitle"><h2>Business Health Score</h2><button>รายละเอียด</button></div><div className="healthRow"><div className="bigScore">87<small>/100</small></div><div><b>ธุรกิจของคุณอยู่ในเกณฑ์ ดีมาก</b><p>เพิ่มขึ้น 5 คะแนนจากสัปดาห์ก่อน</p></div><div className="healthMini">{[['Sales','92/100'],['Inventory','81/100'],['Profit','89/100'],['Customer','91/100'],['Cash Flow','76/100']].map(x=><div key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span/></div>)}</div></div></div>
   <div className="card ecosystem"><div className="cardTitle"><h2>Retail OS Ecosystem</h2><button>View all apps</button></div><div>{[['▯','Mobile Shop','ร้านมือถือ'],['▰','Computer Shop','ร้านคอมพิวเตอร์'],['⌂','Gadget Store','ร้านแกดเจ็ต'],['▣','Electronics','เครื่องใช้ไฟฟ้า'],['🔧','Repair Shop','ร้านซ่อม'],['▤','Marketplace','ขายหลายช่องทาง']].map(x=><button key={x[1]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></button>)}</div></div>
  </section><section className="midDash">
   <div className="card"><div className="cardTitle"><h2>Top Selling Products</h2><button>View all</button></div><ol className="topProducts">{allProducts.slice(0,5).map((p,i)=><li key={p.id}><strong>{i+1}</strong><span className="deviceThumb">▯</span><div><b>{p.name}</b><small>{p.stock||15} Units</small></div><em>{money(p.price*(i+1))}</em></li>)}</ol></div>
   <div className="twoCards"><InfoCard title="Inventory Health" score="1,245" rows={[['ปกติ','812 (65%)'],['ใกล้หมด','210 (17%)'],['ค้างสต็อก','154 (12%)'],['เกิน 90 วัน','69 (6%)']]}/><InfoCard title="Stock Alert" score="⚠" rows={allProducts.slice(0,3).map(p=>[p.name,p.stock<10?'ใกล้หมด':'ค้างสต็อก'])}/></div>
   <div className="twoCards"><InfoCard title="Repair Status" score={String(repairs.length||12)} rows={[['รอรับเครื่อง','12'],['กำลังตรวจสอบ','8'],['รออะไหล่','5'],['กำลังซ่อม','7'],['เสร็จสิ้น','18']]}/><InfoCard title="Installment Overview" score="฿1.28M" rows={[['ครบกำหนดวันนี้','฿85,000'],['เกินกำหนด 1-30 วัน','฿42,500'],['เกินกำหนด 31-60 วัน','฿18,900'],['ยังไม่ถึงกำหนด','฿1,134,100']]}/></div>
  </section><aside className="rightDash">
   <div className="aiCard"><div className="cardTitle"><h2>✦ AI Copilot <sup>BETA</sup></h2></div><div className="ask">ธุรกิจของคุณวันนี้เป็นอย่างไรบ้าง?</div><p>ภาพรวมยอดขายเติบโต <b>12.5%</b><br/>กำไรขั้นต้น 8.7% ดีขึ้นจากเดือนก่อน<br/>มี 3 ประเด็นที่ควรให้ความสนใจ!</p><button onClick={()=>setAiOpen(!aiOpen)}>✦ วิเคราะห์เพิ่มเติม</button></div>
   <div className="card recommendations"><div className="cardTitle"><h2>AI Recommendations</h2><span>3 รายการ</span></div>{['แนะนำลดราคาสินค้า','แนะนำสั่งสินค้าเพิ่ม','โอกาสในการขาย'].map((x,i)=><div key={x}><span className={'rec r'+i}>{i===0?'✧':i===1?'▣':'♙'}</span><section><b>{x}</b><p>{i===0?'iPhone 14 Plus 128GB ค้างสต็อก 61 วัน แนะนำลดราคา 4-6%':i===1?'iPhone 15 Pro 256GB มีความต้องการสูง ควรสั่งเพิ่ม 2-3 วัน':'ลูกค้าที่ซื้อ iPhone 15 มีโอกาสซื้อ AirPods 32%'}</p><button>ดูรายละเอียด</button></section></div>)}</div>
   <div className="card activity"><div className="cardTitle"><h2>Recent Activities</h2><button>View all</button></div>{['ขายสินค้า Invoice #INV-2024-0523-0012','รับเครื่องซ่อม Repair #RP-2024-0523-0008','รับซื้อเครื่อง Trade-In #TI-2024-0523-0005','รับสินค้าเข้า PO #PO-2024-0523-0003'].map((x,i)=><p key={x}><span>{['▣','🔧','♻','▤'][i]}</span>{x}<small>{i===0?'2 นาทีที่แล้ว':i===1?'15 นาทีที่แล้ว':i===2?'28 นาทีที่แล้ว':'1 ชั่วโมงที่แล้ว'}</small></p>)}</div>
  </aside></div></div>
 const InventoryTable=()=> <div className="card tableCard"><div className="cardTitle"><h2>Products & Inventory</h2><span>{filtered.length} products</span></div><table><thead><tr><th>PRODUCT</th><th>BRAND</th><th>PRICE</th><th>STOCK</th><th>ACTION</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><b>{p.name}</b>{p.trackImei&&' · IMEI'}</td><td>{p.brand}</td><td>{money(p.price)}</td><td>{p.stock} units</td><td>{p.trackImei&&<input aria-label={'IMEI '+p.name} inputMode="numeric" maxLength={15} placeholder="IMEI 15 หลัก" value={imeiInput[p.id]??''} onChange={e=>setImeiInput(x=>({...x,[p.id]:e.target.value.replace(/\D/g,'').slice(0,15)}))}/>}<button onClick={()=>runAction(()=>addToCart(p))}>Add to POS</button></td></tr>)}</tbody>{!filtered.length&&<tbody><tr><td colSpan={5}><div className="emptyState">ไม่พบสินค้า ลองค้นหาด้วยชื่อหรือแบรนด์อื่น</div></td></tr></tbody>}</table></div>
 const POS=()=> {const subtotal=cart.reduce((s,i)=>s+i.qty*i.unitPrice-i.discount,0);const tax=Math.round(subtotal*0.07*100)/100;const total=Math.round((subtotal+tax)*100)/100;return <div className="moduleView"><h1>POS หน้าร้าน</h1><p>ขายสินค้า · สแกน Barcode/IMEI · รับชำระเงิน</p><div className="workGrid"><InventoryTable/><div className="card cart"><h2>ตะกร้าสินค้า</h2>{!cart.length&&<div className="emptyState">ตะกร้าสินค้าว่าง เลือกสินค้าเพื่อเริ่มการขาย</div>}{cart.map(i=><p key={i.productId+(i.imei||'')}><b>{i.name}</b><span>{i.qty} × {money(i.unitPrice)}</span></p>)}{cart.length>0&&<><p><span>Subtotal</span><span>{money(subtotal)}</span></p><p><span>VAT 7%</span><span>{money(tax)}</span></p></>}<h3>Total: {money(total)}</h3><input type="number" placeholder="จำนวนเงินที่รับ" value={paid} onChange={e=>setPaid(e.target.value)}/><button className="primaryBtn" disabled={loading} onClick={()=>runAction(completeCheckout)}>{loading?'กำลังประมวลผล...':'ชำระเงิน'}</button></div></div></div>}
 const Products=()=> <div className="moduleView"><h1>สินค้า & สต็อก</h1><p>จัดการสินค้า SKU / Barcode / IMEI / Inventory</p><InventoryTable/></div>
 const Customers=()=> <div className="moduleView"><h1>ลูกค้า (CRM)</h1><div className="form"><input placeholder="ชื่อลูกค้า" value={newCustomer.name} onChange={e=>setNewCustomer({...newCustomer,name:e.target.value})}/><input placeholder="เบอร์โทร" value={newCustomer.phone} onChange={e=>setNewCustomer({...newCustomer,phone:e.target.value})}/><button disabled={loading} onClick={()=>runAction(addCustomer)}>{loading?'กำลังบันทึก...':'เพิ่มลูกค้า'}</button></div><div className="card tableCard"><table><thead><tr><th>NAME</th><th>PHONE</th><th>POINTS</th></tr></thead><tbody>{customers.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.phone}</td><td>{c.loyaltyPoints}</td></tr>)}</tbody></table></div></div>
 const Repairs=()=> <div className="moduleView"><h1>Repair Center</h1><div className="form"><input placeholder="ลูกค้า" value={repair.customer} onChange={e=>setRepair({...repair,customer:e.target.value})}/><input placeholder="อุปกรณ์" value={repair.device} onChange={e=>setRepair({...repair,device:e.target.value})}/><input placeholder="อาการเสีย" value={repair.issue} onChange={e=>setRepair({...repair,issue:e.target.value})}/><button disabled={loading} onClick={()=>runAction(addRepair)}>{loading?'กำลังบันทึก...':'รับเครื่องซ่อม'}</button></div>{repairs.map(r=><div className="card row" key={r.id}><b>{r.customer} · {r.device}</b><span>{r.issue}</span><em>{r.status}</em></div>)}</div>
 const Purchasing=()=> <div className="moduleView"><h1>Purchases</h1><div className="form"><input placeholder="Supplier" value={purchase.supplier} onChange={e=>setPurchase({...purchase,supplier:e.target.value})}/><input type="number" placeholder="จำนวนรายการ" value={purchase.items} onChange={e=>setPurchase({...purchase,items:e.target.value})}/><input type="number" placeholder="ยอดรวม" value={purchase.total} onChange={e=>setPurchase({...purchase,total:e.target.value})}/><button disabled={loading} onClick={()=>runAction(addPurchase)}>{loading?'กำลังบันทึก...':'สร้าง PO'}</button></div>{purchases.map(p=><div className="card row" key={p.id}><b>{p.supplier}</b><span>{p.items} items · {money(p.total)}</span><em>{p.status}</em></div>)}</div>
 const generic=()=> <div className="moduleView"><h1>{active}</h1><p>โมดูล {active} อยู่ใน RetailOS Architecture และพร้อมเชื่อม workflow จริง</p><div className="card placeholder"><b>RetailOS Module</b><span>กำลังแสดงข้อมูลจากระบบ Multi-Tenant ของคุณ</span></div></div>
 const view=active==='Dashboard'?<Dashboard/>:active==='POS'?<POS/>:active==='Products'||active==='IMEI Inventory'||active==='Stock & Transfer'?<Products/>:active==='Customers (CRM)'||active==='Loyalty & Points'?<Customers/>:active==='Repair Center'||active==='Trade-In (รับซื้อ)'?<Repairs/>:active==='Purchases'?<Purchasing/>:generic()
 return <div className="app"><aside className="sidebar"><div className="brand"><span className="brandMark">R</span><div><b>Retail OS</b><small>AI Operating System</small></div></div>{navGroups.map(g=><div className="navGroup" key={g.label}><label>{g.label}</label>{g.items.map(([name,icon])=><button key={name} className={active===name?'active':''} onClick={()=>{setActive(name);if(name==='AI Copilot')setAiOpen(true)}}><span>{icon}</span>{name}</button>)}</div>)}<div className="plan"><b>Enterprise Plan</b><small>12 / 20 Users</small><i><span/></i></div></aside><main className="main"><header className="topbar"><div className="search">⌕<input placeholder="Search anything... (IMEI, SKU, Invoice, Customer, Repair...)" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘K</kbd></div><button className="aiTop" onClick={()=>setAiOpen(!aiOpen)}>✦ AI Copilot</button><div className="topIcons">♧<sup>12</sup> ✉ <span>?</span></div><div className="account"><div>👨🏻</div><section><b>Mobile Hub Co., Ltd.</b><small>Branch A (Central World)</small></section>⌄</div></header><div className="content">{loading&&<div className="loadingState">กำลังประมวลผล...</div>}{error&&<div className="errorState">{error}</div>}{message&&<div className="stateMessage">{message}</div>}{view}</div></main>{aiOpen&&<div className="copilotDrawer"><div><b>✦ AI Copilot</b><button onClick={()=>setAiOpen(false)}>×</button></div><p>ผมพร้อมช่วยวิเคราะห์ธุรกิจของคุณ</p><button>วิเคราะห์ยอดขาย</button><button>ตรวจ Stock Risk</button><button>สร้างคำแนะนำ</button></div>}</div>
}
function InfoCard({title,score,rows}:{title:string;score:string;rows:string[][]}){return <div className="card infoCard"><div className="cardTitle"><h2>{title}</h2><button>View all</button></div><div className="infoScore">{score}</div>{rows.map(r=><p key={r[0]}><span>{r[0]}</span><b>{r[1]}</b></p>)}</div>}
export default App
